### ISSUE TITLE
not able to test my images on pretrained models

### ISSUE THREAD

**Issue by KridaCreations** [lhoyer/improving_segmentation_with_selfsupervised_depth#12]
i am getting this error

Start inference2021-11-13_07-43-52-534157
Traceback (most recent call last):
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\inference.py", line 174, in <module>
    inference_main(cfg)
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\inference.py", line 128, in inference_main
    expand_cfg_vars(cfg)
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\train.py", line 929, in expand_cfg_vars
    expand_cfg_vars(cfg[k])
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\train.py", line 933, in expand_cfg_vars
    cfg[k] = cfg[k].replace(cfg[k].split("/")[0], getattr(MachineConfig, var_name))
AttributeError: type object 'MachineConfig' has no attribute 'LOG_DIR\inference2021-11-13_07-43-52-534157'

**Comment by KridaCreations** [comment]
i have solved this error but now iam getting this error:

C:\Users\Abhishek\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\transforms\transforms.py:287: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\inference.py", line 175, in <module>
    inference_main(cfg)
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\inference.py", line 138, in inference_main
    inference = Inference(cfg, logdir, os.path.join(name, str(run_id)))
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\inference.py", line 53, in __init__
    self.val_loader = build_loader(self.cfg["data"], "val", load_labels=False, load_sequence=False)
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\loader\__init__.py", line 45, in build_loader
    loader = data_loader(
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\loader\inference_loader.py", line 11, in __init__
    super(InferenceLoader, self).__init__(**kwargs)
  File "C:\git_projects\mlproject\improving_segmentation_with_selfsupervised_depth\loader\sequence_segmentation_loader.py", line 114, in __init__
    raise RuntimeError(f"Found no segmentation files in {self.images_base}")
RuntimeError: Found no segmentation files in \data



i have a folder with sequence of images from a video

**Comment by lhoyer** [comment]
Based on the given paths, I guess that you use Windows. The project only supports Linux. Probably, the backslashes of Windows paths mess up the path handling in the source code, which assumes that slashes are used.
